services:
  # 前端靜態網站
  - type: web
    name: zanvoai-portfolio
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # 啟用 PR 預覽
    envVars:
      - key: REACT_APP_API_URL
        value: https://zanvoai-portfolio-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400 # 一天的快取
    routes:
      - type: rewrite
        source: /*
        destination: /index.html